/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolesb;

import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {
    private Arbol arbol;
    public Menu() {
        initComponents();
       // setIconImage(new ImageIcon(getClass().getResource("/Imagenes/fondo_menu_3.jpg")).getImage());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Abol B+");
        
        boton_borrar.setEnabled(false);
        boton_buscar_valor.setEnabled(false);
        boton_imprimir.setEnabled(false);
        boton_insertar.setEnabled(false);
        boton_obtener_altura.setEnabled(false);
        boton_obtener_nivel.setEnabled(false);
        
        boto_CrearArbol.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        boton_borrar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        boton_buscar_valor.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        boton_imprimir.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        boton_insertar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        boton_obtener_altura.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        boton_obtener_nivel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        
        Imagen img1 = new Imagen("/Imagenes/fondo_sistema6.jpg", 807, 453);
        this.Panel.add(img1);
        this.Panel.repaint();
        add(Panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        boto_CrearArbol = new javax.swing.JButton();
        boton_insertar = new javax.swing.JButton();
        boton_borrar = new javax.swing.JButton();
        boton_buscar_valor = new javax.swing.JButton();
        boton_imprimir = new javax.swing.JButton();
        boton_obtener_altura = new javax.swing.JButton();
        boton_obtener_nivel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boto_CrearArbol.setBackground(new java.awt.Color(255, 255, 255));
        boto_CrearArbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolesb/arbol1.1.png"))); // NOI18N
        boto_CrearArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_CrearArbolActionPerformed(evt);
            }
        });

        boton_insertar.setBackground(new java.awt.Color(255, 255, 255));
        boton_insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolesb/agregar2.1.png"))); // NOI18N
        boton_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_insertarActionPerformed(evt);
            }
        });

        boton_borrar.setBackground(new java.awt.Color(255, 255, 255));
        boton_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolesb/eliminar1.1.png"))); // NOI18N
        boton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_borrarActionPerformed(evt);
            }
        });

        boton_buscar_valor.setBackground(new java.awt.Color(255, 255, 255));
        boton_buscar_valor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolesb/buscar1.1.png"))); // NOI18N
        boton_buscar_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar_valorActionPerformed(evt);
            }
        });

        boton_imprimir.setBackground(new java.awt.Color(255, 255, 255));
        boton_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolesb/imprimir1.1.png"))); // NOI18N
        boton_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_imprimirActionPerformed(evt);
            }
        });

        boton_obtener_altura.setBackground(new java.awt.Color(255, 255, 255));
        boton_obtener_altura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolesb/altura1.1.png"))); // NOI18N

        boton_obtener_nivel.setBackground(new java.awt.Color(255, 255, 255));
        boton_obtener_nivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolesb/nivel2.1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crear Arbol");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insertar Valor");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar Valor");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eliminar Valor");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Imprimir Arbol");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Encontrar Altura");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nivel Del Nodo");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(135, 135, 135)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_obtener_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(boton_buscar_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(boton_obtener_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(boton_borrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(59, 59, 59))))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(boto_CrearArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(boto_CrearArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(boton_buscar_valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(boton_insertar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_obtener_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_obtener_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_imprimir))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_borrarActionPerformed
//inicializar el arbol
    private void boto_CrearArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_CrearArbolActionPerformed
            String cadena_grado = JOptionPane.showInputDialog("Ingrese el grado del arbol"), numeroAingresar; 
            int grado;
            try {
             grado = Integer.parseInt(cadena_grado);
             if(grado<=2){
              JOptionPane.showMessageDialog(null,"El grado debe de ser mayor a 2","Advertencia",JOptionPane.WARNING_MESSAGE); 
             }
             else{
                arbol = new Arbol(grado);
                int ValoresMinimos = (grado-1)/2, contador =0, dato;
                JOptionPane.showMessageDialog(null,"A continuacion ingrese los valores minimos","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                while(contador<ValoresMinimos){
                    numeroAingresar = JOptionPane.showInputDialog("Ingrese el valor "+(contador+1));
                    try {
                        dato = Integer.parseInt(numeroAingresar);
                        if(dato<=0){
                           JOptionPane.showMessageDialog(null,"El valor debe de ser mayor a cero","Advertencia",JOptionPane.WARNING_MESSAGE);   
                        }
                        else{
                            arbol.Insertar(dato,arbol.getRaiz());
                            contador++; 
                        }
                       
                    } catch (Exception e) {
                      JOptionPane.showMessageDialog(null,"Llene el campo y solo con valores numericos","Advertencia",JOptionPane.WARNING_MESSAGE);  
                    }
                }
                
                boton_borrar.setEnabled(true);
                boton_buscar_valor.setEnabled(true);
                boton_imprimir.setEnabled(true);
                boton_insertar.setEnabled(true);
                boton_obtener_altura.setEnabled(true);
                boton_obtener_nivel.setEnabled(true);
               
               JOptionPane.showMessageDialog(null,"Arbol creado con exito","Arbol creado",JOptionPane.INFORMATION_MESSAGE); 
                 
             }
        } catch (Exception e) {
           
           JOptionPane.showMessageDialog(null,"Debe de ingresar solo nunmeros","Advertencia",JOptionPane.WARNING_MESSAGE);

        }
        
        
        
            
    }//GEN-LAST:event_boto_CrearArbolActionPerformed
//imprimir el arbol
    private void boton_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_imprimirActionPerformed
        arbol.Mostrar(arbol.getRaiz());
        JOptionPane.showMessageDialog(null,arbol.getCadena(),"Arbol impreso",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_boton_imprimirActionPerformed
//Insertar valores
    private void boton_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_insertarActionPerformed
         String cadena_valores = JOptionPane.showInputDialog("Ingrese la cantidad de valores que quiere insertar"),numeroAingresar;
         try {
            int num_valores= Integer.parseInt(cadena_valores), contador = 0, dato;
            if(num_valores<=0){
             JOptionPane.showMessageDialog(null,"Ingrese un valor mayor a cero","Advertencia",JOptionPane.WARNING_MESSAGE);   
            }
            else{
                while(contador<num_valores){
                    numeroAingresar = JOptionPane.showInputDialog("Ingrese el valor "+(contador+1));
                    try {
                        dato = Integer.parseInt(numeroAingresar);
                        if(dato<=0){
                           JOptionPane.showMessageDialog(null,"El valor debe de ser mayor a cero","Advertencia",JOptionPane.WARNING_MESSAGE);   
                        }
                        else{
                            arbol.Insertar(dato,arbol.getRaiz());
                            contador++; 
                        }
                       
                    } catch (Exception e) {
                      JOptionPane.showMessageDialog(null,"Llene el campo y solo con valores numericos","Advertencia",JOptionPane.WARNING_MESSAGE);  
                    }
                    
                }
                JOptionPane.showMessageDialog(null,"Valores ingresados con exito","Mensaje",JOptionPane.INFORMATION_MESSAGE); 
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,"Ingrese solo valores numericos, y no deje el campo vacio","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_boton_insertarActionPerformed
//buscar valores
    private void boton_buscar_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscar_valorActionPerformed
        String cadena_valor = JOptionPane.showInputDialog("Ingrese el valor que quiere buscar"),numeroAingresar;
        try {
            int valor = Integer.parseInt(cadena_valor), contador = 0, dato;
            if(arbol.Buscar(valor,arbol.getRaiz())){
                JOptionPane.showMessageDialog(null,"El valor "+valor+" existe en el arbol","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                 JOptionPane.showMessageDialog(null,"El valor "+valor+" no existe en el arbol","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Ingrese solo valores numericos, y no deje el campo vacio","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_boton_buscar_valorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton boto_CrearArbol;
    private javax.swing.JButton boton_borrar;
    private javax.swing.JButton boton_buscar_valor;
    private javax.swing.JButton boton_imprimir;
    private javax.swing.JButton boton_insertar;
    private javax.swing.JButton boton_obtener_altura;
    private javax.swing.JButton boton_obtener_nivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
